services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habbo_imager
    working_dir: /src
    ports:
      - "3030:3030"
    stdin_open: true
    tty: true
    networks:
      frontend:
        ipv4_address: 172.38.0.2
    environment:
      - YARN_CACHE_FOLDER=/src/app/.yarn-cache
    volumes:
      - ./imager:/src
      - /var/www:/var/www
    # command: sh -c "yarn start"

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.0.0/24
          gateway: 172.38.0.1

